# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c60e550f2860d97b2e62813377a74d2cf66e165267989b9dff6a5cb854af4cbd9f1f9440db4417c1dc5fb59a6e9d6a968e4ac41a2bb380297f84289d92c8d6b3

test:
  secret_key_base: a2324f90412a48c1fc588e6d966573b6140a8f1ab57d9da21afbfea4b525d233b35f11c6cc5580621c20384f7c31ea1700fed3423c901aef7956600b89af1687

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
